from django.shortcuts import render,redirect
from django.http import HttpResponse
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from .models import blog
from .forms import Edit_Blog
# Create your views here.
def index(request):
    Blog=blog.objects.all()#collect all raw that'swhy we need to use for loop
    context={'blogs':Blog}
    return render(request,'index.html', context)

def user_register(request):
    if request.method == 'POST':
        fname=request.POST.get('fname')
        lname=request.POST.get('lname')
        uname=request.POST.get('uname')
        email=request.POST.get('email')
        pass1=request.POST.get('password')
        pass2=request.POST.get('password2')
        print(fname, lname, uname, email, pass1, pass2)
        
        if pass1!=pass2:
            messages.warning(request, 'Your Password Does not match! Try Again')
            return redirect('register')
        elif User.objects.filter(username=uname).exists():
            messages.warning(request, 'This Username is already exist! Try Different.')
            return redirect('register')
        elif User.objects.filter(email=email).exists():
            messages.warning(request, 'This Email is already taken!.')
            return redirect('register')
        else:
            user = User.objects.create_user(first_name=fname, last_name=lname, email=email, password=pass1, username=uname)
            user.save()
            messages.success(request, 'Your Registration has been completed!')
            return redirect('/')
     
    return render(request,'register.html')
def user_login(request):
    if request.method=='POST':
    
        username=request.POST.get('luname')
        password=request.POST.get('lpassword')
        # print(username, password)
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            # Redirect to a success page.
            messages.success(request, 'You are loged in successfully!')
            return redirect('/')
        else:
            # Return an 'invalid login' error message.
            messages.warning(request, 'Invalid Credential')
            return redirect('login')
    return render(request,'login.html')

def logout_view(request):

    logout(request)
    messages.success(request, 'You are loged Out successfully!')
    return redirect('/')

def post_blog(request):
    if request.method=='POST':
        title=request.POST.get('title')
        desc=request.POST.get('description')
        Blog=blog(title=title, dsc=desc, user_id=request.user)
        Blog.save()
        messages.success(request,'Post has been submitted successfully')
        return redirect('post_blog')
    return render(request, 'post_blog.html')

def blog_detail(request, id):
    Blog= blog.objects.get(id=id)#collect id like 2 or 3 auto generated by django perticular value, don't need to use for loop bcoz there is only one value
    context={'blog':Blog}
    return render(request, 'blog_detail.html',context)


def delete(request, id):
    Blog= blog.objects.get(id=id)
    Blog.delete()
    messages.success(request, 'Post has been deleted successfully')
    return redirect('/')

def edit(request, id):
    Blog= blog.objects.get(id=id)
    edit_blog= Edit_Blog(instance=Blog)#instance = Blog will give already written text of writer to my edit page 
    if request.method=='POST':
        form = Edit_Blog(request.POST, instance=Blog)#instance = Blog so django will know i want to do some changes on it
        if form.is_valid():
            form.save()
            messages.success(request, 'Post has been Updated successfully')
            return redirect('/')

    return render(request, 'edit_blog.html', {'edit_blog':edit_blog})